# Generated by Django 2.2 on 2019-06-25 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='gtype',
            new_name='gType',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='isselling',
            new_name='isSelling',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='isbncode',
            new_name='isbnCode',
        ),
    ]
