# Generated by Django 2.2 on 2019-06-28 09:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190625_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='detail',
            field=tinymce.models.HTMLField(max_length=200, verbose_name='details(.html)'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='repertory',
            field=models.PositiveIntegerField(verbose_name='repertory'),
        ),
    ]
