# Generated by Django 2.2 on 2019-06-25 22:52

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20190625_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecieveInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever', models.CharField(max_length=50, verbose_name='reciever_name')),
                ('address', models.TextField(verbose_name='recive_address')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='reciever_phone')),
                ('postcode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='order_code')),
                ('createAt', models.DateTimeField(verbose_name='create_at')),
                ('goodsList', django_mysql.models.JSONField(default=dict)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='total_price')),
                ('isPaid', models.BooleanField()),
                ('isDelivered', models.BooleanField()),
                ('remarks', models.TextField(default='None')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Customer', verbose_name='customer')),
                ('rcvInfo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.RecieveInfo', verbose_name='reciever_info')),
            ],
        ),
    ]
