# Generated by Django 2.2 on 2019-06-25 22:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createAt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='create_at'),
        ),
    ]
