# Generated by Django 2.2 on 2019-06-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190625_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updateAt',
            field=models.DateTimeField(auto_now=True, verbose_name='update_at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create_at'),
        ),
    ]
