# Generated by Django 2.2 on 2019-06-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190626_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createAt',
            field=models.DateTimeField(default='2019-06-26 17:39:21.512456+00:00', verbose_name='create_at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updateAt',
            field=models.DateTimeField(default='2019-06-26 17:39:21.512510+00:00', verbose_name='update_at'),
        ),
    ]
