# Generated by Django 2.2 on 2019-06-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20190627_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createAt',
            field=models.DateTimeField(default='2019-06-26 17:41:24.043957+00:00', verbose_name='create_at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updateAt',
            field=models.DateTimeField(default='2019-06-26 17:41:24.043997+00:00', verbose_name='update_at'),
        ),
    ]
