# Generated by Django 2.2 on 2019-06-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20190628_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.PositiveIntegerField(choices=[(1, 'online'), (0, 'cash')], default=1, max_length=2, verbose_name='payment method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updateAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
