# Generated by Django 2.2 on 2019-06-28 15:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clerk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=40, verbose_name='password')),
                ('realName', models.CharField(max_length=50, verbose_name='real_name')),
                ('group', models.CharField(max_length=10)),
                ('lastLogin', models.DateTimeField(default=django.utils.timezone.now)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('isOnline', models.BooleanField(default=False)),
                ('jobnumber', models.CharField(max_length=11)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=40, verbose_name='password')),
                ('realName', models.CharField(max_length=50, verbose_name='real_name')),
                ('group', models.CharField(max_length=10)),
                ('lastLogin', models.DateTimeField(default=django.utils.timezone.now)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('isOnline', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='phone_number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('account', models.FloatField(default=1000.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecieveInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever', models.CharField(max_length=50, verbose_name='reciever_name')),
                ('address', models.TextField(verbose_name='recive_address')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='reciever_phone')),
                ('postcode', models.CharField(max_length=6)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Customer', verbose_name='customer')),
            ],
        ),
    ]
