# Generated by Django 2.2 on 2019-06-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerk',
            name='group',
            field=models.CharField(choices=[('1', 'Customer'), ('0', 'Clerk')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='group',
            field=models.CharField(choices=[('1', 'Customer'), ('0', 'Clerk')], default='1', max_length=10),
        ),
    ]
