# Generated by Django 2.2 on 2019-06-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clerk',
            old_name='realname',
            new_name='realName',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='realname',
            new_name='realName',
        ),
        migrations.AddField(
            model_name='clerk',
            name='createAt',
            field=models.DateTimeField(default=0, verbose_name='create_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clerk',
            name='lastLogin',
            field=models.DateTimeField(default=0, verbose_name='last_login'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clerk',
            name='updateAt',
            field=models.DateTimeField(default=0, verbose_name='update_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='createAt',
            field=models.DateTimeField(default=0, verbose_name='create_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='lastLogin',
            field=models.DateTimeField(default=0, verbose_name='last_login'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='updateAt',
            field=models.DateTimeField(default=0, verbose_name='update_at'),
            preserve_default=False,
        ),
    ]
