# Generated by Django 2.2 on 2019-06-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190625_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerk',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create_at'),
        ),
        migrations.AlterField(
            model_name='clerk',
            name='lastLogin',
            field=models.DateTimeField(auto_now=True, verbose_name='last_login'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create_at'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastLogin',
            field=models.DateTimeField(auto_now=True, verbose_name='last_login'),
        ),
    ]
