# Generated by Django 2.2 on 2019-06-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190625_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerk',
            name='createAt',
            field=models.DateTimeField(default='2019-06-25 23:30:15', verbose_name='create_at'),
        ),
        migrations.AlterField(
            model_name='clerk',
            name='lastLogin',
            field=models.DateTimeField(default='2019-06-25 23:30:15', verbose_name='last_login'),
        ),
        migrations.AlterField(
            model_name='clerk',
            name='updateAt',
            field=models.DateTimeField(default='2019-06-25 23:30:15', verbose_name='update_at'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='createAt',
            field=models.DateTimeField(default='2019-06-25 23:30:15', verbose_name='create_at'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastLogin',
            field=models.DateTimeField(default='2019-06-25 23:30:15', verbose_name='last_login'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updateAt',
            field=models.DateTimeField(default='2019-06-25 23:30:15', verbose_name='update_at'),
        ),
    ]
