# Generated by Django 2.2 on 2019-06-28 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliver',
            name='recieveInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.RecieveInfo'),
        ),
    ]
