# Generated by Django 2.2 on 2019-06-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20190625_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliver',
            name='createAt',
            field=models.DateTimeField(default='2019-06-25 23:30:15'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='createAt',
            field=models.DateTimeField(default='2019-06-25 23:30:15'),
        ),
    ]
