# Generated by Django 2.2 on 2019-06-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_auto_20190625_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliver',
            name='createAt',
            field=models.DateTimeField(default='2019-06-25 23:44:29.344416'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='createAt',
            field=models.DateTimeField(default='2019-06-25 23:44:29.344416'),
        ),
    ]
